## Exploring data using Numpy

In [1]:
import numpy as np

Create and list

In [2]:
my_list = [1,2,3,4,5]

In [3]:
my_array = np.array(my_list)

In [4]:
my_array * 2

array([ 2,  4,  6,  8, 10])

In [5]:
my_list * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Return evenly spaced number

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Random

In [9]:
np.random.rand(10)

array([0.84030268, 0.48759933, 0.4609045 , 0.49181121, 0.28542809,
       0.5233015 , 0.16920141, 0.83308034, 0.40870425, 0.27351456])

In [10]:
np.random.randn(10)

array([-0.18870397, -0.96723514,  0.78351739, -0.10285302,  0.36045275,
       -1.11325703,  1.29701546,  2.2832305 ,  0.75189953, -1.32913328])

Create a list of list of grade

In [13]:
data = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
print(data)

[50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]


In [15]:
grade = np.array(data)
print(grade)

[50 50 47 97 49  3 53 42 26 74 82 62 37 15 70 27 36 35 48 52 63 64]


In [17]:
print(data * 2)

[50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64, 50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]


It shows that when we multiple a list we produce any list by the multiple values

In [18]:
print(grade * 2)

[100 100  94 194  98   6 106  84  52 148 164 124  74  30 140  54  72  70
  96 104 126 128]


Whene we multiple a numpy array, we are multipling the individual values of the array but not reproducing the array

In [19]:
# Get the shape of the array
grade.shape

(22,)

It shows that the array is a one dimensional array and 22 elements

In [23]:
# Get the first element in an array
grade[0]

50

In [24]:
# Get the last element in an array
grade[-1]

64

In [25]:
# Get the minimum value in an array
grade.min()

3

In [26]:
# Get the maximum value in an array
grade.max()

97

In [27]:
# Get the mean of the array
grade.mean()

49.18181818181818

It shows that the mean of the grades are just 49, which is also most the middle of the data

In [30]:
# Adding another datasets
study_hours = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]

In [31]:
# Convert the list to numpy array
study_hours = np.array(study_hours)

In [32]:
print(study_hours)

[10.   11.5   9.   16.    9.25  1.   11.5   9.    8.5  14.5  15.5  13.75
  9.    8.   15.5   8.    9.    6.   10.   12.   12.5  12.  ]


In [35]:
# Create a 2D data
student_record = np.array([study_hours, grade])

In [36]:
# Get the shape of the data
student_record.shape

(2, 22)

In [38]:
print(student_record)

[[10.   11.5   9.   16.    9.25  1.   11.5   9.    8.5  14.5  15.5  13.75
   9.    8.   15.5   8.    9.    6.   10.   12.   12.5  12.  ]
 [50.   50.   47.   97.   49.    3.   53.   42.   26.   74.   82.   62.
  37.   15.   70.   27.   36.   35.   48.   52.   63.   64.  ]]


We see that we now have two elements containing 22 elements each

In [39]:
# Extract the first element from the student data
student_record[0][0]

10.0

In [44]:
# Get the mean of each record
study_hours_avg = student_record[0].mean()
grade_avg = student_record[1].mean()

print(f'The mean for Study hours id {study_hours_avg}\nThe mean for the grade is {grade_avg}')

The mean for Study hours id 10.522727272727273
The mean for the grade is 49.18181818181818


## Exploring Data using Pandas

In [45]:
import pandas as pd 

In [47]:
# help(pd.DataFrame)

Create a dictionary of students

In [57]:
# Create a list of Names
name = ['Dan', 'Joann', 'Pedro', 'Rosie', 'Ethan', 'Vicky', 'Frederic', 'Jimmie', 
                                     'Rhonda', 'Giovanni', 'Francesca', 'Rajab', 'Naiyana', 'Kian', 'Jenny',
                                     'Jakeem','Helena','Ismat','Anila','Skye','Daniel','Aisha']

In [59]:
print(name)

['Dan', 'Joann', 'Pedro', 'Rosie', 'Ethan', 'Vicky', 'Frederic', 'Jimmie', 'Rhonda', 'Giovanni', 'Francesca', 'Rajab', 'Naiyana', 'Kian', 'Jenny', 'Jakeem', 'Helena', 'Ismat', 'Anila', 'Skye', 'Daniel', 'Aisha']


In [55]:
# Create an empty DataFrame
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [62]:
# Create a record of student
df_student = pd.DataFrame({'Name':name,
                          'HoursStudied': student_record[0],
                         'Grade':student_record[1]})

In [63]:
df_student

Name  HoursStudied  Grade
0         Dan         10.00   50.0
1       Joann         11.50   50.0
2       Pedro          9.00   47.0
3       Rosie         16.00   97.0
4       Ethan          9.25   49.0
5       Vicky          1.00    3.0
6    Frederic         11.50   53.0
7      Jimmie          9.00   42.0
8      Rhonda          8.50   26.0
9    Giovanni         14.50   74.0
10  Francesca         15.50   82.0
11      Rajab         13.75   62.0
12    Naiyana          9.00   37.0
13       Kian          8.00   15.0
14      Jenny         15.50   70.0
15     Jakeem          8.00   27.0
16     Helena          9.00   36.0
17      Ismat          6.00   35.0
18      Anila         10.00   48.0
19       Skye         12.00   52.0
20     Daniel         12.50   63.0
21      Aisha         12.00   64.0

In [64]:
# Extract the first five rows
df_student.head()

Name  HoursStudied  Grade
0    Dan         10.00   50.0
1  Joann         11.50   50.0
2  Pedro          9.00   47.0
3  Rosie         16.00   97.0
4  Ethan          9.25   49.0

In [65]:
# Extract the last five rows
df_student.tail()

Name  HoursStudied  Grade
17   Ismat           6.0   35.0
18   Anila          10.0   48.0
19    Skye          12.0   52.0
20  Daniel          12.5   63.0
21   Aisha          12.0   64.0

Finding and extracting data from DataFrame

In [67]:
# Extract the data located in index number 5
df_student.loc[5]

Name            Vicky
HoursStudied      1.0
Grade             3.0
Name: 5, dtype: object

In [68]:
# Extract data located in index number 3
df_student.loc[3]

Name            Rosie
HoursStudied     16.0
Grade            97.0
Name: 3, dtype: object

In [69]:
# Extract the record from index 0 to 5
df_student.loc[0:5]

Name  HoursStudied  Grade
0    Dan         10.00   50.0
1  Joann         11.50   50.0
2  Pedro          9.00   47.0
3  Rosie         16.00   97.0
4  Ethan          9.25   49.0
5  Vicky          1.00    3.0

In [70]:
# Get the first five rows from the DataFrame
df_student.iloc[0:5]

Name  HoursStudied  Grade
0    Dan         10.00   50.0
1  Joann         11.50   50.0
2  Pedro          9.00   47.0
3  Rosie         16.00   97.0
4  Ethan          9.25   49.0

In [71]:
# Get the data from position number 1
df_student.iloc[1,[1,2]]

HoursStudied    11.5
Grade           50.0
Name: 1, dtype: object

In [72]:
# Return the grade from index 1
df_student.loc[1, 'Grade']

50.0

In [73]:
# Return the grade from index 2
df_student.loc[2,'Grade']

47.0

In [74]:
# Return the house studied from index 2
df_student.loc[2,'HoursStudied']

9.0

In [75]:
# Extract the row where the name is Rosie
df_student[df_student['Name']=='Rosie']

Name  HoursStudied  Grade
3  Rosie          16.0   97.0

In [76]:
# Extract the row where the name is Joann
df_student.loc[df_student['Name']=='Joann']

Name  HoursStudied  Grade
1  Joann          11.5   50.0

## Loading data from a file

In [77]:
filepath = 'grades.csv'
df = pd.read_csv(filepath)
df.head()

Name  StudyHours  Grade
0    Dan       10.00   50.0
1  Joann       11.50   50.0
2  Pedro        9.00   47.0
3  Rosie       16.00   97.0
4  Ethan        9.25   49.0

In [79]:
# Check data types of the data
df.info();

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        24 non-null     object 
 1   StudyHours  23 non-null     float64
 2   Grade       22 non-null     float64
dtypes: float64(2), object(1)
memory usage: 704.0+ bytes


In [80]:
# Check for null values
df.isnull()

Name  StudyHours  Grade
0   False       False  False
1   False       False  False
2   False       False  False
3   False       False  False
4   False       False  False
5   False       False  False
6   False       False  False
7   False       False  False
8   False       False  False
9   False       False  False
10  False       False  False
11  False       False  False
12  False       False  False
13  False       False  False
14  False       False  False
15  False       False  False
16  False       False  False
17  False       False  False
18  False       False  False
19  False       False  False
20  False       False  False
21  False       False  False
22  False       False   True
23  False        True   True

In [81]:
# Count the number of null values
df.isnull().sum()

Name          0
StudyHours    1
Grade         2
dtype: int64

In [83]:
# Return the rows that have the missing values 
df[df.isnull().any(axis=1)]

Name  StudyHours  Grade
22  Bill         8.0    NaN
23   Ted         NaN    NaN

In [84]:
# Using impute replacement to replace the missing values for the hours studies
StudyHours_mean = df['StudyHours'].mean()
StudyHours_mean

10.41304347826087

In [85]:
df['StudyHours'] = df['StudyHours'].fillna(StudyHours_mean)

In [86]:
# Count the number of null values
df.isnull().sum()

Name          0
StudyHours    0
Grade         2
dtype: int64

In [88]:
# Drop the NaN from the data
df = df.dropna(axis=0, how='any')

In [89]:
# Count the number of null values
df.isnull().sum()

Name          0
StudyHours    0
Grade         0
dtype: int64

## Exploring Data in a DataFrame

In [91]:
# Extract the mean for the grade
mean_grade = df['Grade'].mean()

# Extract the mean for the Studied hours
mean_studiedh = df.StudyHours.mean()

print('The mean for the Grade is {:.2f}\nThe mean for the Hours studied is {:.2f}'.format(mean_grade,mean_studiedh))

The mean for the Grade is 49.18
The mean for the Hours studied is 10.52


In [92]:
# Extract the students that studied more than the mean
df[df['StudyHours']>mean_studiedh]

Name  StudyHours  Grade
1       Joann       11.50   50.0
3       Rosie       16.00   97.0
6    Frederic       11.50   53.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
14      Jenny       15.50   70.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

In [93]:
# Extract students who score above the mean
df[df['Grade']>mean_grade]

Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
3       Rosie       16.00   97.0
6    Frederic       11.50   53.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
14      Jenny       15.50   70.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

In [97]:
# Get the student who scored above 60 and put that in a variable and call it pass
passed = pd.Series(df['Grade']>60)
passed

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11     True
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20     True
21     True
Name: Grade, dtype: bool

In [98]:
df = pd.concat([df, passed.rename('PASS')], axis=1)
df

Name  StudyHours  Grade   PASS
0         Dan       10.00   50.0  False
1       Joann       11.50   50.0  False
2       Pedro        9.00   47.0  False
3       Rosie       16.00   97.0   True
4       Ethan        9.25   49.0  False
5       Vicky        1.00    3.0  False
6    Frederic       11.50   53.0  False
7      Jimmie        9.00   42.0  False
8      Rhonda        8.50   26.0  False
9    Giovanni       14.50   74.0   True
10  Francesca       15.50   82.0   True
11      Rajab       13.75   62.0   True
12    Naiyana        9.00   37.0  False
13       Kian        8.00   15.0  False
14      Jenny       15.50   70.0   True
15     Jakeem        8.00   27.0  False
16     Helena        9.00   36.0  False
17      Ismat        6.00   35.0  False
18      Anila       10.00   48.0  False
19       Skye       12.00   52.0  False
20     Daniel       12.50   63.0   True
21      Aisha       12.00   64.0   True

In [100]:
# Group the record by pass
df.groupby(df['PASS']).count()

Name  StudyHours  Grade
PASS                          
False    15          15     15
True      7           7      7

In [101]:
# Group the record by pass
df.groupby(df['PASS']).Name.count()

PASS
False    15
True      7
Name: Name, dtype: int64

In [ ]:
THEN END